services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RP_ID=localhost
      - RP_ORIGIN=http://localhost:5001
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
